Contacts
naf24/goitbootcamp16-team2 pull request #6
Opened 2022-03-22 16:52 UTC by iwillywonka94

Чорновий варіант контактів

2022-03-22 19:22 UTC, Andari757 requested changes

2022-03-22 19:22 UTC, Andari757 commented on src/partials/contacts.html
> +                <span class="institution__title foodtruck">FOODTRUCK</span>
На таблетці та десктопі має бути пробіл між словами

2022-03-22 19:22 UTC, Andari757 commented on src/partials/contacts.html
> +                        <a href="tel:+61(0)383766284" class="contacts__link link">+61(0) 383 766 284</a>
не такий line-height

2022-03-22 19:22 UTC, Andari757 commented on src/partials/contacts.html
> +                        <p class="location__text">Fusce ut velit laoreet, tempus arcu molestie vulputate</p>
не такий line-height

2022-03-22 19:22 UTC, Andari757 commented on src/sass/layouts/_contacts.scss
> +        padding: 30px 0;
мені здається, що padding тут не застосовувати недоцільно, для відступів краще використовувати margin

2022-03-22 19:22 UTC, Andari757 commented on src/partials/contacts.html
> +                    <li class="institution__item work">
трохи не по бем'у, чотири `p` знизу то наврядче окремий блок, бо він не має сенсу сам по собі. Якщо треба додатковий клас - модифікатор то це не просто work, а institution__item--work. Далі так само з contacts.

2022-03-22 19:22 UTC, Andari757 commented on src/sass/layouts/_contacts.scss
> +    padding: 50px 32px;
не такий padding на декстопі

2022-03-23 07:20 UTC, naf24 commented on src/partials/contacts.html
> +                        <p class="location__text">Fusce ut velit laoreet, tempus arcu molestie vulputate</p>
кмкпкр

2022-03-23 07:37 UTC, iwillywonka94 reviewed
upd

2022-03-23 07:37 UTC, iwillywonka94 commented on src/sass/layouts/_contacts.scss
> +        padding: 30px 0;
Використав padding тому що при використанні margin відбувається зливання, тобто у першої li margin-bot зєднується з margin top другої li, і залишається 30px замість очікуваних 60 які необхідні)

2022-03-23 07:37 UTC, iwillywonka94 commented on src/sass/layouts/_contacts.scss
> +    padding: 50px 32px;
На десктопі padding такий як вказаний, якщо подивитись від <span> CAFE </span> то padding-top 50px і padding-left 31px

2022-03-23 07:37 UTC, iwillywonka94 commented on src/partials/contacts.html
> +                        <a href="tel:+61(0)383766284" class="contacts__link link">+61(0) 383 766 284</a>
Виправив

2022-03-23 07:37 UTC, iwillywonka94 commented on src/partials/contacts.html
> +                        <p class="location__text">Fusce ut velit laoreet, tempus arcu molestie vulputate</p>
Виправив

2022-03-23 08:34 UTC, Andari757 commented on src/sass/layouts/_contacts.scss
> +    padding: 50px 32px;
![image](https://user-images.githubusercontent.com/96066311/159656997-d30738ce-1884-4d48-a76f-6f719d667d29.png)

2022-03-23 13:29 UTC, naf24 approved these changes, later dismissed

2022-03-23 13:51 UTC, naf24 approved these changes, later dismissed

2022-03-23 15:38 UTC, Andari757 commented on src/sass/layouts/_contacts.scss
> +        @media screen and (min-width: 1200px) {
точка перелому 1280

2022-03-23 15:42 UTC, Andari757 approved these changes

2022-03-23 15:44 UTC, Andari757 commented on src/sass/layouts/_contacts.scss
> +    @media screen and (min-width: 1200px) {
точка перелому 1280

2022-03-23 16:33 UTC, merged